bosh2 create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/azure/cpi.yml \
    -v director_name=boshinfra \
    -v internal_cidr=172.28.1.0/26 \
    -v internal_gw=172.28.1.1 \
    -v internal_ip=172.28.1.11 \
    -v vnet_name=oss-bosh-infra-virtual-network \
    -v subnet_name=oss-bosh-infra-subnet \
    -v subscription_id=REPLACE_ME \
    -v tenant_id=REPLACE_ME \
    -v client_id=REPLACE_ME \
    -v client_secret=REPLACE_ME \
    -v resource_group_name=oss-bosh-infra \
    -v storage_account_name=boshinfrastorage \
    -v default_security_group=boshinfrasg
