---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cgicloudnative/cfjump

params:
  JUMPBOX_ACTION:
  IAAS_DIRECTORY:
  IAAS_USERNAME:
  IAAS_PASSWORD:

inputs:
  - name: automation-scripts

outputs:
 - name: jumpbox-keys

run:
  path: automation-scripts/ci/scripts/create-jumpbox.sh
