---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ramxx/cfjump-alpine
    tag: "v0.2"

inputs:
  - name: automation-scripts

outputs:
 - name: jumpbox-keys

run:
  path: automation-scripts/ci/scripts/create-jumpbox.sh
