---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ramXX/cfjump-alpine

inputs:
  - name: automation-scripts

outputs:
 - name: jumpbox-keys

run:
  path: automation-scripts/ci/scripts/create-jumpbox.sh
