---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cgicloudnative/cfjump

params:
  JUMPBOX_ACTION:
  IAAS_DIRECTORY:
  CONFIG_DIRECTORY:
  AZURE_USERNAME:
  AZURE_PASSWORD:

inputs:
  - name: automation-scripts

outputs:
 - name: jumpbox-artifacts

run:
  path: automation-scripts/ci/scripts/create-jumpbox.sh
