---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cgicloudnative/cfjump

inputs:
  - name: automation-scripts

outputs:
 - name: jumpbox-artifacts

run:
  path: automation-scripts/ci/scripts/create-jumpbox.sh
