---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cgicloudnative/cfjump 

inputs:
  - name: automation-scripts
  - name: jumpbox-artifacts

run:
  path: automation-scripts/ci/scripts/destroy-jumpbox.sh
