
resources:
- name: automation-scripts
  type: git
  source:
    branch: master
    uri: {{scripts-git-uri}}
    username: {{scripts-git-username}}
    password: {{scripts-git-password}}

jobs:
- name: jumpbox-automation
  plan:
  - aggregate:
    - get: automation-scripts
  - task: Create
    file: {{create-jumpbox-script}}
    params:
      JUMPBOX_ACTION: apply
      IAAS_DIRECTORY: {{iaas-directory}}
      VSPHERE_USERNAME: ((vsphere-username))
      VSPHERE_PASSWORD: ((vsphere-password))
      INIT_VM_USERNAME: {{init-vm-username}}
      INIT_VM_PASSWORD: {{init-vm-password}}
  - task: Verify
    file: {{verify-jumpbox-script}}
    params:
      JUMPBOX_ACTION: verify
      IAAS_DIRECTORY: {{iaas-directory}}
      VSPHERE_USERNAME: ((vsphere-username))
      VSPHERE_PASSWORD: ((vsphere-password))
