
resources:
- name: automation-scripts
  type: git
  source:
    branch: master
    uri: {{scripts-git-uri}}
    username: ((git-svc-user))
    password: ((git-svc-password))
    ignore_paths:
    - README.md
    - .gitignore
    - ci/pipeline.yml

jobs:
- name: jumpbox-automation
  plan:
  - aggregate:
    - get: automation-scripts
      trigger: true
  - do:
    - task: Create
      file: {{create-jumpbox-script}}
      params:
        JUMPBOX_ACTION: apply
        IAAS_DIRECTORY: {{iaas-directory}}
        AWS_ACCESS_KEY: ((aws-access-key-id))
        AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
        AWS_KEY_NAME: gold-environment
        AWS_PREFIX: jumpbox
        AWS_REGION: us-east-1
        AWS_AZ1: us-east-1a
        AWS_PRIVATE_KEY: ((aws-private-key))
        AZURE_USERNAME: ((azure-username))
        AZURE_PASSWORD: ((azure-password))
        VSPHERE_USERNAME: ((vsphere-username))
        VSPHERE_PASSWORD: ((vsphere-password))
        VSPHERE_DOMAIN: lab.ecsteam.local
        VSPHERE_SERVER: ecsdenlabvc01.lab.ecsteam.local
        INIT_VM_USERNAME: ((init-vm-username))
        INIT_VM_PASSWORD: ((init-vm-password))
        GCP_PROJECT: ((gcp-project-id))
        GCP_CREDS_FILE: ((gcp-gold-service-account-key))
        CREDS_TYPE: ((gcp-creds-type))
        CREDS_PROJECT_ID: ((gcp-creds-project-id))
        CREDS_PRIVATE_KEY_ID: ((gcp-creds-private-key-id))
        CREDS_PRIVATE_KEY: ((gcp-creds-private-key))
        CREDS_EMAIL: ((gcp-creds-email))
        CREDS_CLIENT_ID: ((gcp-creds-client-id))
        CREDS_CERT_URL: ((gcp-creds-cert-url))
    - task: Verify
      file: {{verify-jumpbox-script}}
      params:
        JUMPBOX_ACTION: verify
        AWS_KEY_NAME: gold-environment
        INIT_VM_USERNAME: ((init-vm-username))
        IAAS_DIRECTORY: {{iaas-directory}}
        VSPHERE_USERNAME: ((vsphere-username))
        VSPHERE_PASSWORD: ((vsphere-password))
    ensure:
      task: Destroy
      file: {{destroy-jumpbox-script}}
      params:
        JUMPBOX_ACTION: destroy
        AWS_ACCESS_KEY: ((aws-access-key-id))
        AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
        AZURE_USERNAME: ((azure-username))
        AZURE_PASSWORD: ((azure-password))
        IAAS_DIRECTORY: {{iaas-directory}}
        VSPHERE_USERNAME: ((vsphere-username))
        VSPHERE_PASSWORD: ((vsphere-password))
        VSPHERE_DOMAIN: lab.ecsteam.local
        VSPHERE_SERVER: ecsdenlabvc01.lab.ecsteam.local
        GCP_PROJECT: ((gcp-project-id))
        GCP_CREDS_FILE: ((gcp-gold-service-account-key))
        CREDS_TYPE: ((gcp-creds-type))
        CREDS_PROJECT_ID: ((gcp-creds-project-id))
        CREDS_PRIVATE_KEY_ID: ((gcp-creds-private-key-id))
        CREDS_PRIVATE_KEY: ((gcp-creds-private-key))
        CREDS_EMAIL: ((gcp-creds-email))
        CREDS_CLIENT_ID: ((gcp-creds-client-id))
        CREDS_CERT_URL: ((gcp-creds-cert-url))
