
resources:
- name: automation-scripts
  type: git
  source:
    branch: master
    uri: {{scripts-git-uri}}
    username: ((git-srv-user))
    password: ((git-srv-password))

jobs:
- name: jumpbox-automation
  plan:
  - aggregate:
    - get: automation-scripts
  - do:
    - task: Create
      file: {{create-jumpbox-script}}
      params:
        JUMPBOX_ACTION: apply        
        IAAS_DIRECTORY: {{iaas-directory}}
        AWS_ACCESS_KEY: ((aws-access-key-id))
        AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
        AWS_KEY_NAME: gold-environment
        AZURE_USERNAME: ((azure-username))
        AZURE_PASSWORD: ((azure-password))
        VSPHERE_USERNAME: ((vsphere-username))
        VSPHERE_PASSWORD: ((vsphere-password))
        INIT_VM_USERNAME: ((init-vm-username))
        INIT_VM_PASSWORD: ((init-vm-password))
        CREDS_TYPE: ((gcp-creds-type))
        CREDS_PROJECT_ID: ((gcp-creds-project-id))
        CREDS_PRIVATE_KEY_ID: ((gcp-creds-private-key-id))
        CREDS_PRIVATE_KEY: ((gcp-creds-private-key))
        CREDS_EMAIL: ((gcp-creds-email))
        CREDS_CLIENT_ID: ((gcp-creds-client-id))
        CREDS_CERT_URL: ((gcp-creds-cert-url))
    - task: Verify
      file: {{verify-jumpbox-script}}
      params:
        JUMPBOX_ACTION: verify
        IAAS_DIRECTORY: {{iaas-directory}}
        VSPHERE_USERNAME: ((vsphere-username))
        VSPHERE_PASSWORD: ((vsphere-password))
    ensure:
      task: Destroy
      file: {{destroy-jumpbox-script}}
      params:
        JUMPBOX_ACTION: destroy
        AZURE_USERNAME: ((azure-username))
        AZURE_PASSWORD: ((azure-password))
        IAAS_DIRECTORY: {{iaas-directory}}
        VSPHERE_USERNAME: ((vsphere-username))
        VSPHERE_PASSWORD: ((vsphere-password))
        CREDS_TYPE: ((gcp-creds-type))
        CREDS_PROJECT_ID: ((gcp-creds-project-id))
        CREDS_PRIVATE_KEY_ID: ((gcp-creds-private-key-id))
        CREDS_PRIVATE_KEY: ((gcp-creds-private-key))
        CREDS_EMAIL: ((gcp-creds-email))
        CREDS_CLIENT_ID: ((gcp-creds-client-id))
        CREDS_CERT_URL: ((gcp-creds-cert-url))