
resources:
- name: automation-scripts
  type: git
  source:
    branch: master
    uri: {{scripts-git-uri}}
    username: ((git-srv-user))
    password: ((git-srv-password))

jobs:
- name: jumpbox-automation
  plan:
  - aggregate:
    - get: automation-scripts
  - do:
    - task: Create
      file: {{create-jumpbox-script}}
      output: jumpbox-artifacts
      params:
        JUMPBOX_ACTION: apply
        IAAS_DIRECTORY: {{iaas-directory}}
        IAAS_USERNAME: {{iaas-username}}
        IAAS_PASSWORD: {{iaas-password}}
        INIT_VM_USERNAME: {{init-vm-username}}
        INIT_VM_PASSWORD: {{init-vm-password}}
        CREDS_TYPE: {{CREDS_TYPE}}
        CREDS_PROJECT_ID: {{CREDS_PROJECT_ID}}
        CREDS_PRIVATE_KEY_ID: {{CREDS_PRIVATE_KEY_ID}}
        CREDS_PRIVATE_KEY: {{CREDS_PRIVATE_KEY}}
        CREDS_EMAIL: {{CREDS_EMAIL}}
        CREDS_CLIENT_ID: {{CREDS_CLIENT_ID}}
        CREDS_CERT_URL: {{CREDS_CERT_URL}}
    - task: Verify
      file: {{verify-jumpbox-script}}
      input: jumpbox-artifacts
      params:
        JUMPBOX_ACTION: verify
        IAAS_DIRECTORY: {{iaas-directory}}
        IAAS_USERNAME: {{iaas-username}}
        IAAS_PASSWORD: {{iaas-password}}
    ensure:
      task: Destroy
      file: {{destroy-jumpbox-script}}
      params:
        JUMPBOX_ACTION: destroy
        IAAS_DIRECTORY: {{iaas-directory}}
        IAAS_USERNAME: {{iaas-username}}
        IAAS_PASSWORD: {{iaas-password}}
        CREDS_TYPE: {{CREDS_TYPE}}
        CREDS_PROJECT_ID: {{CREDS_PROJECT_ID}}
        CREDS_PRIVATE_KEY_ID: {{CREDS_PRIVATE_KEY_ID}}
        CREDS_PRIVATE_KEY: {{CREDS_PRIVATE_KEY}}
        CREDS_EMAIL: {{CREDS_EMAIL}}
        CREDS_CLIENT_ID: {{CREDS_CLIENT_ID}}
        CREDS_CERT_URL: {{CREDS_CERT_URL}}