
resources:
- name: automation-scripts
  type: git
  source:
    branch: master
    uri: {{scripts-git-uri}}
    username: {{scripts-git-username}}
    password: {{scripts-git-password}}

jobs:
- name: jumpbox-automation
  plan:
  - aggregate:
    - get: automation-scripts
  - task: Create
    file: {{create-jumpbox-script}}
    params:
      JUMPBOX_ACTION: apply
      IAAS_DIRECTORY: {{iaas-directory}}
      IAAS_USERNAME: {{iaas-username}}
      IAAS_PASSWORD: {{iaas-password}}
      VM_INIT_USERNAME: {{init-vm-username}}
      VM_INIT_PASSWORD: {{init-vm-password}}
  - task: Verify
    file: {{verify-jumpbox-script}}
    params:
      JUMPBOX_ACTION: verify
      IAAS_DIRECTORY: {{iaas-directory}}
      IAAS_USERNAME: {{iaas-username}}
      IAAS_PASSWORD: {{iaas-password}}
  - task: Destroy
    file: {{destroy-jumpbox-script}}
    params:
      JUMPBOX_ACTION: destroy
      IAAS_DIRECTORY: {{iaas-directory}}
      IAAS_USERNAME: {{iaas-username}}
      IAAS_PASSWORD: {{iaas-password}}
