
resources:
- name: automation-scripts
  type: git
  source:
    branch: master
    uri: {{scripts-git-uri}}
    username: {{scripts-git-username}}
    password: {{scripts-git-password}}

jobs:
- name: Create Jumpbox
  plan:
  - aggregate:
    - get: automation-scripts
  - task: Create
    file: {{create-jumpbox-script}}
    params:
      JUMPBOX_ACTION: apply
      IAAS_DIRECTORY: {{iaas-directory}}
      IAAS_USERNAME: {{iaas-username}}
      IAAS_PASSWORD: {{iaas-password}}